server:
    port: 9000
settings:
    SAMPLE_DB: 2017_01_21_11_02_55_sample.db
    SPEECH_DATA_FOLDER_PATH: /usr/local/anki_note/speech/
    SPEECH_DATA_TEMP_FOLDER_PATH: /usr/local/anki_note/speech_tmp/